### ISSUE TITLE
Retrain the paper result

### ISSUE THREAD

**Issue by Zongwei97** [JiaweiZhao-git/DASNet#3]
Thanks and congrats for the great work!

I am trying to retrain the RGBD model. However, I cannot reproduce the same result as presented in the paper. With the same setting, I get 0.029 and  0.0528 MAE for NLPR and NJUD.

Do u have any idea why this happens ? Did I miss something ?

**Comment by JiaweiZhao-git** [comment]
Did you train the model with the provided training/testing sets on the project page?

**Comment by Zongwei97** [comment]
Yes or non. The testing dataset is not provided in this github. As for training, you didn't provide the .txt file.
But since the training/testing sets are common datasets, I am quasi-sure that I use the same sets.
